# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-24 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bijia',
            name='comment',
            field=models.IntegerField(default=0),
        ),
    ]
