# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-24 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('goods', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfro')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('content', models.CharField(default='', max_length=100)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('goods', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfro')),
                ('manager', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.ManagerMessage')),
            ],
        ),
        migrations.CreateModel(
            name='order_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goods', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfro')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=14, unique=True)),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=150)),
                ('contacts', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(default='', max_length=20)),
                ('pay_status', models.BooleanField(default=False)),
                ('pay_time', models.DateTimeField(null=True)),
                ('send_status', models.BooleanField(default=False)),
                ('send_time', models.DateTimeField(null=True)),
                ('receive_status', models.BooleanField(default=False)),
                ('receive_time', models.DateTimeField(null=True)),
                ('comment_status', models.BooleanField(default=False)),
                ('manage', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.ManagerMessage')),
            ],
        ),
        migrations.CreateModel(
            name='user_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('name', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(default='', max_length=50)),
                ('activate', models.BooleanField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user_address',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.users'),
        ),
        migrations.AddField(
            model_name='orders',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.users'),
        ),
        migrations.AddField(
            model_name='order_info',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.orders'),
        ),
        migrations.AddField(
            model_name='comment',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.users'),
        ),
        migrations.AddField(
            model_name='car',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.users'),
        ),
    ]
