# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-27 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managermessage',
            name='nicheng',
        ),
        migrations.RemoveField(
            model_name='managermessage',
            name='shop_address',
        ),
        migrations.RemoveField(
            model_name='managermessage',
            name='shop_name',
        ),
    ]
